
name: Regenerate README.md

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '32 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build readme
      run: |
        python build.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git config --global user.email "rasjani@users.noreply.github.com"
        git config --global user.name "BuildBot"
        git diff
        git add  README.md
        git commit -m "Updated content" || exit 0
        git push
